Mergedbackground tasks and master
Klint02/P7-PSEngine pull request #30
Opened 2024-12-13 11:34 UTC by D-Kuma-C

2024-12-13 13:07 UTC, TorbjoernH approved these changes
En smule uhøfligt

2024-12-17 11:17 UTC, Klint02 requested changes
Vi tager lige nogle af kommentarene til et møde

2024-12-17 11:17 UTC, Klint02 commented on src/P7-PSEngine/Data/PSengineDB.cs
> +                entity.HasKey(e => new { e.FileId, e.UserId });
Filers key inde i databasen skal også indeholde cloudservice ID de er forbundet til, for at fjerne chancen for duplicate keys

2024-12-17 11:17 UTC, Klint02 commented on src/CloudSearcher/DropboxGetter.cs
> +}
Er dette et seperat projekt eller bruges den nu i stedet for dbox handleren?

2024-12-17 11:17 UTC, Klint02 commented on src/P7-PSEngine/DTO/DropboxDTO.cs
> +    }*/
Duplicate code; det udkommenteret kode ligner cloudsearcher koden

2024-12-17 11:17 UTC, Klint02 commented on src/P7-PSEngine/Handlers/DropBoxHandler.cs
> +
Hvis der alligevel skal ændres på brackets osv. samt laves cleanup, så gør det ordentligt.
Fjern de tomme linjer der nu er kommet

2024-12-17 11:17 UTC, Klint02 commented on src/P7-PSEngine/Handlers/GoogleDriveHandler.cs
> +    public async Task<bool> ProcessFiles(WebApplication app, User user, string? path, CloudService service, IInvertedIndexService indexService)
Hvad er pointen med denne metode?

2024-12-17 11:17 UTC, Klint02 commented on src/P7-PSEngine/Model/FileInformation.cs
> +
Tomme linjer efter oprydning................

2024-12-17 11:17 UTC, Klint02 commented on src/P7-PSEngine/Model/User.cs
> +
Tomme linjer...........

2024-12-17 13:49 UTC, Klint02 approved these changes

2024-12-17 13:52 UTC, merged